name: PR Checks 

on:
  pull_request
  
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checks out repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Run rubocop
        run: bundle exec rubocop
      - name: Run specs
        run: bundle exec rspec spec/
        
