name: PR Checks 

on:
  pull_request
  
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checks out repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Install dependencies
        run: |
          sudo apt-get -yqq install libpq-dev
          gem install bundler -v '2.1.2'
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
      - name: Run rubocop
        run: bundle exec rubocop
      - name: Run specs
        run: bundle exec rspec spec/
        
